<a href="https://colab.research.google.com/github/Ovizero01/Python-Machine-Learning/blob/main/010_Numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = [1,2,3]
print( arr * 5 )
arr = [ x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [3]:
arr1 = np.array([1,2,3])
arr1 = arr1 * 5
print(arr1)

[ 5 10 15]


# Ndarray

In [4]:
# 1d array
arr1 = np.array([1,2,3,4,5])


# 2d array
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])

#3d array
arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2
])


# Array attributes

In [5]:
# dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 3)
(3, 2, 3)
int64
int64
int64
5
6
18


# ndarray data type

In [6]:
arr = np.array([1,2,3])

print(arr.dtype)

arr = np.array([1.5,2.4,3.2])
print(arr.dtype)

int64
float64


In [7]:
arr = np.array([1,2,3.2])
# upcasted to float
print(arr.dtype)

#upcasted to string
arr = np.array([1,2,3.2,'hello'])
print(arr.dtype)


arr = np.array([1,True,3.25,'hello',])
print(arr.dtype)

float64
<U32
<U32


# selecting a data type for an array

In [8]:
arr = np.array([1,2,300],dtype=np.int16)
print(arr.dtype)
print(arr)

arr = arr.astype(np.int32)
print(arr.dtype)

#error
arr = np.array([1,2,3.2,'hello'],dtype=np.float64)

int16
[  1   2 300]
int32


ValueError: could not convert string to float: 'hello'

# ndarray creation from existing data

In [9]:
#list

lst = [10,20,30,40 , 40.5]

arr = np.array(lst, dtype=np.int32)

# print(arr)
# print(type(arr))
# print(arr.dtype)

mixed_lst = [10, True , 'Hello' ]

arr = np.array(mixed_lst)

# print(arr)
# print(type(arr))
# print(arr.dtype)


matrix = [ [1,2,3], # row1
           [4,5,6] #row2
                ]

arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [10]:
#tuple

tpl = (10,20,30)

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [11]:
#set

st = { 1, 2, 3 }

arr = np.array(list(st))
# print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [12]:
# dictionary

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()

In [13]:
#keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [14]:
#values to ndarray
arr = np.array(list(values))
print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1
3


In [15]:
#items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


# Creating ndarray from scratch

In [16]:
# np.zeros

arr = np.zeros((2,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.zeros_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)


In [17]:
#np.ones

arr = np.ones((3,4,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.ones_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [18]:
#np.empty
arr = np.empty((4,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.empty_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [19]:
#np.full

arr = np.full((4,3),np.inf)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.full_like(arr3,np.inf,dtype=np.float64)

print(arr)
print(arr.shape)
print(arr.dtype)

[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(3, 2, 3)
float64


# array creation with random values

In [20]:
# np.random.rand(shape)

arr = np.random.rand(2,3) # 0 ->1

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.10945628 0.0102231  0.62397314]
 [0.42871133 0.95237733 0.02752048]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [21]:
# np.random.randint(start,end, shape)

arr = np.random.randint(1,10 , (2,3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[6 2 1]
 [8 9 5]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
6


In [22]:
# np.random.uniform(start,end, shape)

arr = np.random.uniform(50,100, (3,3,4))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[99.29664912 55.91559657 82.13537901 56.28786745]
  [74.60037634 65.26480675 52.96242817 76.62500456]
  [55.33239584 61.78484572 70.5051969  90.7274459 ]]

 [[95.19616271 91.53601102 71.76972341 55.52161885]
  [91.30493959 87.23298849 83.99950527 90.69858623]
  [77.29716616 68.24108952 59.93226743 85.9163009 ]]

 [[51.55234973 53.12226262 72.15472347 61.69960488]
  [60.75177972 82.24574074 64.90167204 61.77382852]
  [88.73429341 99.14104966 76.53092207 52.6584782 ]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


# array creation with range functions

In [23]:
# np.arange(first , end , step ) -> similar to range function

arr = np.arange(1 , 10 ,1 )
mat = arr.reshape(3,3)

print(arr)
print(mat)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [24]:
# np.linspace(start , end(included) , koita)

arr = np.linspace(0, 4 ,6)


print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [25]:
# np.logspace(start , end(included) , koita )

arr = np.logspace(0 , 4 ,6, base =2)

print(arr)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


# creating matrix for Linear algebra

In [26]:
diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [27]:
# identity matrix

identity_mat = np.eye(4)
# print(identity_mat)
# print(identity_mat.shape)

# np.eye(row , column,k)

mat = np.eye(3,4)
print(mat)

mat = np.eye(3,4,1)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# indexing and slicing

In [28]:
#indexing

print(arr1)
print(arr2)

# arr1[2] = 100

# print(arr1)
arr2[0][2]= 100

print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[  1   2 100]
 [  4   5   6]]


In [29]:
#slicing
#1d = arr[start:end:step]

arr1_mod = arr1[1:4].copy()
arr1[1] = 2


arr1_mod[2] = 200
print(arr1_mod)
print(arr1)

[  2   3 200]
[1 2 3 4 5]


In [30]:
#2d slicing
# arr[ row_start : row_end : step , column_start : column_end : step ]

# print(arr2)

#getting a row

row_0 = arr2[0:1 ,]

row_1= arr2[1: , ]

# print(row_0)
# print(row_1)


#getting a column

col_0 = arr2[:: ,0:1]
col_1 = arr2[::,1:2]

print(col_0)
print(col_1)

#getting a portion


portion = arr2[:: , 0:2]

print(portion)

[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]


# Advanced Indexing

In [31]:
lst = np.array([ 10 , 20 ,30 ,40 ])

values = lst[[0,3,1]]

print(values)

[10 40 20]


In [38]:
print(arr2)
print(arr2[[0,1] , [1,2]])

# boolean kono kichu diye
arr2[arr2>2] = 0

print(arr2)

[[1 2 0]
 [0 0 0]]
[2 0]
[[1 2 0]
 [0 0 0]]


In [39]:
print(arr2)

[[1 2 0]
 [0 0 0]]


In [36]:
arr  = np.array([[10,20,30] , [100,200,300] ] )

# iteration
print(arr3)
for i in np.nditer(arr3):
    print(i)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
2
3
4
5
6
1
2
3
4
5
6
1
2
3
4
5
6
