<a href="https://colab.research.google.com/github/Ovizero01/Python-Machine-Learning/blob/main/011_Numpy02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
arr = np.random.randint(1 ,100 , size =(10,5)) # sample - 10 , feature - 5

In [18]:
arr.shape

(10, 5)

In [19]:
b = arr.reshape(5,10)
b.shape
b.ndim
b

array([[63, 76, 44, 55, 87, 38, 44, 34, 23, 45],
       [63, 96, 33, 53, 24, 13, 31, 14, 33, 20],
       [55, 47, 79, 59, 98, 55, 49,  7, 11, 32],
       [10, 13, 13,  2, 24, 25, 83, 83, 41, 11],
       [92, 17, 27, 40, 53, 92, 54, 23, 93, 31]])

In [20]:
flatten = b.flatten()
print(flatten.ndim)
flatten

column_wise_flattening = np.ravel(b,order= 'C')

print(column_wise_flattening)

1
[63 76 44 55 87 38 44 34 23 45 63 96 33 53 24 13 31 14 33 20 55 47 79 59
 98 55 49  7 11 32 10 13 13  2 24 25 83 83 41 11 92 17 27 40 53 92 54 23
 93 31]


In [21]:
a = np.random.randint(1 ,10 , size =(2,3))
b = np.random.randint(20 ,30 , size =(2,3))
print(a)
print(b)

[[1 8 1]
 [7 8 7]]
[[20 24 21]
 [25 24 20]]


# concatenate

In [22]:
con_row = np.concatenate((a,b),axis=0) # row wise
print(con_row)
con_col = np.concatenate((a,b), axis = 1) # column wise
print(con_col)

[[ 1  8  1]
 [ 7  8  7]
 [20 24 21]
 [25 24 20]]
[[ 1  8  1 20 24 21]
 [ 7  8  7 25 24 20]]


In [23]:
# error

# row wise concetanate korar shomoi column same thakbe
# col wise concat korar shomoi row ta same thakte hobe

x = np.random.randint(1 ,10 , size =(2,3))
y = np.random.randint(1 ,10 , size =(1,3))

r = np.concatenate((x,y),axis =0 )
r = np.concatenate((x,y),axis =1 )
print(r)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [24]:
# transpose

mat = np.array([[10,20,30],
                [30,40,50]
               ])
transpose = mat.T
print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [25]:
# array split

a = np.random.randint(1 ,10 , size =(10,))
print(a)
splitted_array = np.array_split(a,3)

print(splitted_array)

# split -> equal division
splitted_array = np.split(a,3)

[7 9 6 4 3 2 8 5 3 6]
[array([7, 9, 6, 4]), array([3, 2, 8]), array([5, 3, 6])]


ValueError: array split does not result in an equal division

# arithmetic operator and mathematical functions

In [26]:
# faster for vectorization

x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ])

add = np.add(x,y)
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

remainder = x % y

print(remainder)

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [27]:
# mathematical function

# trigonometry

# sin , cos , tan takes values in radian

sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

# deg2rad

[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]


In [28]:
#log

x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)


two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt= np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [33]:
# different
s = np.sum(x)
print(s)

#prefix sum
cumul = np.cumsum(x)
print(cumul)

134
[ 10  18  34 134]


In [34]:
#broadcasting

x = np.array([ 10 , 8 , 16 , 100 ])

result = x + 2

#rulings = columns er size and vector er size same hote hobe

matrix = np.array([[10,20,30],
                [30,40,50]
               ])
result = matrix + 2

vector = np.array([1,2,3,4])

result = matrix +vector
print(result)

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

# Logical Function

In [35]:
# comparison - >,< , >= ,<= , == , !=

x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ])

greater_than = x>y

print(greater_than)

equal = x==y

print(equal)

# all () -> shob true kina
# any() -> jekono ekta true ase kina

print(np.all(greater_than))

print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


# Sorting

In [36]:
#inplace
x = np.array([ 10 , 8 , 16 , 100 ])

z = x.copy()

print(z)

z.sort()

print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [37]:
# copy sorting
print(x)
sort_arr = np.sort(x)

print(sort_arr)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [38]:
# 2d array sorting
mat = np.array([[10,3,5],[8,4,9]])

# horizon axis = 1

hor_sort = np.sort(mat,axis=1)
print(hor_sort)

vert_sort = np.sort(mat,axis=0)
print(vert_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


# Searching

In [39]:
print(x)

[ 10   8  16 100]


In [40]:
# np.where( condition , x , y ) if true x , otherwise replace with y

index = np.where(x==8) # returns index
print(index)

arr = np.where(x>8,x,0) # returns array
print(arr)

(array([1]),)
[ 10   0  16 100]


In [41]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [42]:
index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8,mat,0) # returns array
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [43]:
x = np.array([ 10,100 , 8 , 16 , 100 ])

maximum_value_indx = np.argmax(x)
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

1
2


# counting in ndarray

In [44]:
a = np.random.randint(1 ,100 , size =(100,))
print(a)

[39 43 22 57 77 23 57 57 98 36 42 54 97 98 58 30  8 71 95 86 98 60 51 88
 87 43 32 88 52 45  4 41 92 48 11 98 69 79 18 65 15 87 91 61 75 25 64  6
 41 93 18  1 71 68 95 11 21 61 84 83 89 48 11 29 84 87 93 28 43 10 32 31
 31 56 47 69 97 10 71 20 51 67 50 42  6 80 10 77 47 40 54 23 85 77 80 89
 56 20 94  2]


In [45]:
value_great_than_60 = np.count_nonzero(a==97)
print(value_great_than_60)

2


In [46]:
unique_value,count = np.unique(a,return_counts=True)

print(unique_value)
print(count)

[ 1  2  4  6  8 10 11 15 18 20 21 22 23 25 28 29 30 31 32 36 39 40 41 42
 43 45 47 48 50 51 52 54 56 57 58 60 61 64 65 67 68 69 71 75 77 79 80 83
 84 85 86 87 88 89 91 92 93 94 95 97 98]
[1 1 1 2 1 3 3 1 2 2 1 1 2 1 1 1 1 2 2 1 1 1 2 2 3 1 2 2 1 2 1 2 2 3 1 1 2
 1 1 1 1 2 3 1 3 1 2 1 2 1 1 3 2 2 1 1 2 1 2 2 4]


# statistical function

In [49]:
#data load

data = np.genfromtxt('student_scores.csv' ,delimiter=',',skip_header=1)

print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [50]:
# statistics
math_marks = data[::,:1]

print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

# standard deviation

std_math_marks = np.std(math_marks)
print(std_math_marks)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


In [51]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


# linear algebra

In [52]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe
dot_product = np.dot(A,B)
print(dot_product)


# trace
print(np.trace(B))

[[ 58  64]
 [139 154]]
17


In [54]:
sq_mat = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])
det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)

print(rank_sq)

0.0
2


In [55]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]
